const KEY="finance-v5";
const EXPENSE_CATS=[
  ["Makan","🍜","飲食"],["Jajan","🧋","點心"],["Belanja","🛒","購物"],["Online","📦","網購"],["Transport","🚗","交通"],["Tagihan","💡","帳單"],["Kesehatan","🏥","醫療"],["Hiburan","🎬","娛樂"],["Liburan","🏖️","旅遊"],["Lainnya","📝","其他"]
];
const INCOME_CATS=[["Gaji","💰","薪資"],["Bonus","🎉","獎金"],["Hadiah","🎁","禮物"],["Transfer","↔️","轉入"],["Lainnya","📝","其他"]];
const CAT_ICONS=Object.fromEntries([...EXPENSE_CATS,...INCOME_CATS].map(x=>[x[0],x[1]]));
const CAT_ZH=Object.fromEntries([...EXPENSE_CATS,...INCOME_CATS].map(x=>[x[0],x[2]]));
const T={
 id:{title:"Catatan Keuangan",main:"Total saldo",income:"Pemasukan",expense:"Pengeluaran",accounts:"Akun",transactions:"Transaksi",calendarTransactions:"Kalender & Transaksi",showMoreTransactions:"Lihat lebih banyak transaksi",showLessTransactions:"Sembunyikan transaksi lama",calendarTitle:"Kalender",chartTitle:"Ringkasan pengeluaran",recurringManage:"Pengeluaran tetap per bulan",recurringAdd:"Tambah tagihan tetap",home:"Beranda",settings:"Pengaturan",categoriesNav:"Kategori",add:"Tambah",edit:"Edit",delete:"Hapus",save:"Simpan",cancel:"Batal",name:"Nama",amount:"Nominal",opening:"Saldo Awal",type:"Jenis",category:"Kategori",account:"Akun",note:"Catatan",date:"Tanggal",incomeType:"Pemasukan",expenseType:"Pengeluaran",language:"Bahasa",currency:"Mata uang",theme:"Tema",light:"Terang",dark:"Gelap",hide:"Sembunyikan saldo",show:"Tampilkan saldo",openingMonth:"Saldo awal bulan",transactionAdd:"Tambah transaksi",accountAdd:"Tambah akun",reset:"Hapus semua data",resetConfirm:"Hapus semua data aplikasi?",noTx:"Belum ada transaksi 📝",noDateTx:"Belum ada transaksi di tanggal ini 📅",emptyAccounts:"Belum ada akun 👛",emptyRecurring:"Belum ada tagihan tetap 🧾",deleteConfirm:"Yakin ingin menghapus?",saved:"Data berhasil disimpan ✨",deleted:"Data berhasil dihapus 🗑️",bank:"Bank",ewallet:"E-Wallet",cash:"Tunai",recurringPaid:"Sudah dibayar",recurringUnpaid:"Belum dibayar",markPaid:"Tandai sudah dibayar",paidThisMonth:"Sudah dibayar bulan ini",filterAmount:"Cari nominal",filterCategory:"Kategori",all:"Semua",month:"Bulan",previous:"Sebelumnya",next:"Berikutnya",categories:"Kategori",manageCategories:"Kelola kategori",data:"Data",backup:"Backup data",restore:"Pulihkan data",exported:"Backup siap disimpan ✨",imported:"Data berhasil dipulihkan ✨",danger:"Zona berbahaya",budgetTitle:"Budget Bulanan",savingsTitle:"Target Tabungan",setBudget:"Atur budget",setSavings:"Atur target",budgetUsed:"Terpakai bulan ini",budgetLeft:"Sisa budget",noBudget:"Belum ada budget bulan ini 🎯",savingsTarget:"Target",savedAmount:"Sudah ditabung",progress:"Progress"},
 zh:{title:"記帳小幫手",main:"總餘額",income:"收入",expense:"支出",accounts:"帳戶",transactions:"交易",calendarTransactions:"日曆與交易",showMoreTransactions:"查看更多交易",showLessTransactions:"隱藏較早的交易",calendarTitle:"日曆",chartTitle:"支出摘要",recurringManage:"每月固定支出",recurringAdd:"新增固定支出",home:"首頁",settings:"設定",categoriesNav:"分類",add:"新增",edit:"編輯",delete:"刪除",save:"儲存",cancel:"取消",name:"名稱",amount:"金額",opening:"初始餘額",type:"類型",category:"分類",account:"帳戶",note:"備註",date:"日期",incomeType:"收入",expenseType:"支出",language:"語言",currency:"貨幣",theme:"主題",light:"淺色",dark:"深色",hide:"隱藏餘額",show:"顯示餘額",openingMonth:"本月初始餘額",transactionAdd:"新增交易",accountAdd:"新增帳戶",reset:"刪除全部資料",resetConfirm:"確定要刪除全部資料嗎？",noTx:"還沒有交易唷～ 📝",noDateTx:"這天還沒有交易唷～ 📅",emptyAccounts:"還沒有帳戶唷～ 👛",emptyRecurring:"還沒有固定支出唷～ 🧾",deleteConfirm:"確定要刪除嗎？",saved:"已成功儲存 ✨",deleted:"已成功刪除 🗑️",bank:"銀行",ewallet:"電子錢包",cash:"現金",recurringPaid:"已付款",recurringUnpaid:"尚未付款",markPaid:"標記為已付款",paidThisMonth:"本月已付款",filterAmount:"搜尋金額",filterCategory:"分類",all:"全部",month:"月份",previous:"上個月",next:"下個月",categories:"分類",manageCategories:"管理分類",data:"資料",backup:"備份資料",restore:"還原資料",exported:"備份已準備好 ✨",imported:"資料已成功還原 ✨",danger:"危險操作",budgetTitle:"每月預算",savingsTitle:"儲蓄目標",setBudget:"設定預算",setSavings:"設定目標",budgetUsed:"本月已使用",budgetLeft:"剩餘預算",noBudget:"還沒有設定本月預算唷～ 🎯",savingsTarget:"目標",savedAmount:"已存下",progress:"進度"}
};
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function monthKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function defaultCategories(){return [...EXPENSE_CATS.map(x=>({id:id(),name:x[0],nameZh:x[2],emoji:x[1],kind:"expense"})),...INCOME_CATS.map(x=>({id:id(),name:x[0],nameZh:x[2],emoji:x[1],kind:"income"}))]}
const defaultData={language:"id",currency:"IDR",theme:"light",hidden:false,accounts:[{id:id(),name:"Bank Utama",type:"bank",openingBalance:0},{id:id(),name:"E-Wallet",type:"ewallet",openingBalance:0},{id:id(),name:"Tunai",type:"cash",openingBalance:0}],categories:defaultCategories(),transactions:[],recurring:[],budget:0,target:{name:"",amount:0,progress:0},selectedDate:today(),calendarMonth:monthKey()};
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||"null");if(!raw)return structuredClone(defaultData);const x={...structuredClone(defaultData),...raw};x.accounts=(raw.accounts||structuredClone(defaultData.accounts)).map(a=>({...a,openingBalance:Number(a.openingBalance||0)}));x.categories=(raw.categories||structuredClone(defaultData.categories)).map(c=>({...c,emoji:c.emoji||CAT_ICONS[c.name]||"📝",nameZh:c.nameZh||CAT_ZH[c.name]||c.name}));x.transactions=raw.transactions||[];x.recurring=raw.recurring||[];x.budget=Number(raw.budget||0);x.target=raw.target||{name:"",amount:0,progress:0};return x}catch{return structuredClone(defaultData)}}
let data=load();
// Saat aplikasi dibuka, kalender selalu mengikuti tanggal hari ini.
// Ini hanya dijalankan saat startup; memilih tanggal lain tetap bisa dilakukan tanpa di-reset setiap render.
data.selectedDate=today();
data.calendarMonth=monthKey(new Date());
let visibleTransactionCount=5;
const modal=document.getElementById("modal"); let returnScroll=0;
function t(){return T[data.language]}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function categoryByName(name){return data.categories.find(c=>c.name===name)}
function catLabel(name){const c=categoryByName(name);return data.language==="zh"?(c?.nameZh||CAT_ZH[name]||name):name}
function catIcon(name){const c=categoryByName(name);return c?.emoji||CAT_ICONS[name]||"📝"}
function money(n){if(data.hidden)return "••••••";const locale=data.currency==="IDR"?"id-ID":data.currency==="MYR"?"ms-MY":"zh-TW";return new Intl.NumberFormat(locale,{style:"currency",currency:data.currency,maximumFractionDigits:0}).format(Number(n)||0)}
function currentMonthTx(){const m=monthKey();return data.transactions.filter(x=>x.date?.slice(0,7)===m)}
function totals(){return currentMonthTx().reduce((o,x)=>{if(x.type==="income")o.in+=+x.amount;if(x.type==="expense")o.ex+=+x.amount;return o},{in:0,ex:0})}
function recalc(){data.accounts.forEach(a=>a.balance=Number(a.openingBalance||0));for(const x of data.transactions){if(x.type==="income"){const a=data.accounts.find(a=>a.id===x.accountId);if(a)a.balance+=+x.amount}else if(x.type==="expense"){const a=data.accounts.find(a=>a.id===x.accountId);if(a)a.balance-=+x.amount}else if(x.type==="transfer"){const a=data.accounts.find(a=>a.id===x.from),b=data.accounts.find(a=>a.id===x.to);if(a)a.balance-=+x.amount;if(b)b.balance+=+x.amount}}}
function persist(renderNow=true){localStorage.setItem(KEY,JSON.stringify(data));if(renderNow)render()}
function openModal(title,body){returnScroll=window.scrollY;document.getElementById("modalTitle").textContent=title;document.getElementById("modalBody").innerHTML=body;modal.classList.add("open")}
function closeModal(restore=true){modal.classList.remove("open");if(restore)setTimeout(()=>window.scrollTo(0,returnScroll),0)}
document.getElementById("closeModal").onclick=()=>closeModal();modal.onclick=e=>{if(e.target===modal)closeModal()};
function amountInput(idName,value=0){return `<input id="${idName}" class="amount-input" type="text" inputmode="decimal" autocomplete="off" value="${Number(value)||0}">`}
function wireAmount(idName){const el=document.getElementById(idName);if(!el)return;el.addEventListener("focus",()=>{if(el.value==="0")el.value=""});el.addEventListener("blur",()=>{if(el.value.trim()==="")el.value="0"});el.addEventListener("input",()=>{el.value=el.value.replace(/[^0-9]/g,"").replace(/^0+(?=\d)/,"")||"0"})}
function toast(msg){const el=document.createElement("div");el.className="toast";el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.classList.add("show"),20);setTimeout(()=>{el.classList.remove("show");setTimeout(()=>el.remove(),220)},1700)}
function saveAndClose(msg=t().saved){persist();closeModal();toast(msg)}
function applyLang(){const x=t();document.getElementById("appTitle").textContent=x.title;document.getElementById("mainBalanceLabel").textContent=x.main;document.getElementById("incomeLabel").textContent=x.income;document.getElementById("expenseLabel").textContent=x.expense;document.getElementById("accountsTitle").textContent=x.accounts;document.getElementById("calendarTitle").textContent=x.calendarTransactions||x.calendarTitle;document.getElementById("chartTitle").textContent=x.chartTitle;document.getElementById("recurringTitle").textContent=x.recurringManage;document.getElementById("allTransactionsTitle").textContent=data.language==="zh"?"全部交易":"Semua transaksi";document.getElementById("budgetTitle").textContent=x.budgetTitle;document.getElementById("savingsTitle").textContent=x.savingsTitle;document.getElementById("accountSwipeHint").textContent=data.language==="zh"?"點擊錢包查看帳戶":"Tekan dompet untuk melihat akun";document.getElementById("navHome").textContent=x.home;document.getElementById("navTransactions").textContent=x.transactions;document.getElementById("navSettings").textContent=x.settings;document.getElementById("navCategories").textContent=x.categoriesNav;document.getElementById("hideBalanceBtn").title=data.hidden?x.show:x.hide;document.documentElement.lang=data.language==="id"?"id":"zh-Hant"}
function renderAccounts(){const el=document.getElementById("accountList");const x=t();const types=["cash","bank","ewallet"];const icons={cash:"💵",bank:"🏦",ewallet:"💳"};el.innerHTML=types.map(type=>`<button class="wallet-card ${type}" onclick="openWallet('${type}')"><div class="wallet-icon">${icons[type]}</div><div class="wallet-name">${esc(x[type])}</div><span class="wallet-arrow">›</span></button>`).join("")+`<button class="wallet-add" onclick="addAccount()"><span>＋</span><strong>${data.language==="zh"?"新增錢包":"Tambah Dompet Baru"}</strong></button>`} 
function openWallet(type){const x=t(),list=data.accounts.filter(a=>a.type===type).sort((u,v)=>u.name.localeCompare(v.name));const icon={cash:"💵",bank:"🏦",ewallet:"💳"}[type];const title=`${icon} ${x[type]}`;const rows=list.length?list.map(a=>`<article class="account ${a.type}"><div class="account-top"><span class="account-type">${esc(x[a.type]||a.type)}</span><div class="account-card-actions"><button class="account-edit" aria-label="${esc(x.edit)}" title="${esc(x.edit)}" onclick="editAccount('${a.id}')">✎</button><button class="account-edit" aria-label="${esc(x.delete)}" title="${esc(x.delete)}" onclick="deleteAccount('${a.id}')">🗑️</button></div></div><div class="account-name">${esc(a.name)}</div><div class="account-balance">${money(a.balance||0)}</div><div class="account-opening">${esc(x.openingMonth)}: ${money(a.openingBalance||0)}</div></article>`).join(""):`<div class="empty">${x.emptyAccounts}</div>`;openModal(title,`<div class="wallet-detail-list wallet-grid">${rows}</div><button class="primary" id="addInsideWallet">＋ ${esc(x.accountAdd)}</button>`);document.getElementById("addInsideWallet").onclick=()=>addAccount({type});}
function renderCalendar(){const [yy,mm]=data.calendarMonth.split("-").map(Number);const first=new Date(yy,mm-1,1),days=new Date(yy,mm,0).getDate(),start=(first.getDay()+6)%7;const names=data.language==="zh"?["一","二","三","四","五","六","日"]:["Sn","Sl","Rb","Km","Jm","Sb","Mg"];document.getElementById("calendarMonthLabel").textContent=new Intl.DateTimeFormat(data.language==="zh"?"zh-TW":"id-ID",{month:"long",year:"numeric"}).format(first);document.getElementById("calendarWeekdays").innerHTML=names.map(n=>`<span>${n}</span>`).join("");const counts={};data.transactions.forEach(x=>counts[x.date]=(counts[x.date]||0)+1);let html=Array(start).fill('<button class="cal-day empty"></button>').join("");for(let d=1;d<=days;d++){const ds=`${yy}-${String(mm).padStart(2,"0")}-${String(d).padStart(2,"0")}`;html+=`<button class="cal-day ${counts[ds]?"has-tx":""} ${data.selectedDate===ds?"selected":""}" onclick="selectDate('${ds}')">${d}${counts[ds]?"<i></i>":""}</button>`}document.getElementById("calendarGrid").innerHTML=html;renderCalendarFilters();renderSelectedDateTx()}
function renderCalendarFilters(){const x=t(),amount=document.getElementById("calendarAmountFilter"),cat=document.getElementById("calendarCategoryFilter");if(!amount||!cat)return;document.getElementById("filterAmountLabel").textContent=x.amount;document.getElementById("filterCategoryLabel").textContent=x.category;amount.placeholder=x.filterAmount;const current=cat.value;const cats=[...new Map(data.categories.map(z=>[z.id,z.name])).entries()];cat.innerHTML=`<option value="">${x.all}</option>`+cats.sort((a,b)=>catLabel(a[1]).localeCompare(catLabel(b[1]))).map(([id,name])=>`<option value="${esc(id)}">${catIcon(name)} ${esc(catLabel(name))}</option>`).join("");if(cats.some(([id])=>id===current))cat.value=current;amount.oninput=()=>renderSelectedDateTx();cat.onchange=()=>renderSelectedDateTx()}
function renderSelectedDateTx(){const x=t(),amount=(document.getElementById("calendarAmountFilter")?.value||"").replace(/[^0-9]/g,"");const cat=document.getElementById("calendarCategoryFilter")?.value||"";const rows=data.transactions.filter(z=>z.date===data.selectedDate).filter(z=>!amount||String(Math.round(Number(z.amount)||0)).includes(amount)).filter(z=>!cat||z.categoryId===cat||z.categoryName===cat).sort((a,b)=>b.id.localeCompare(a.id));document.getElementById("selectedDateLabel").textContent=new Date(data.selectedDate+"T00:00:00").toLocaleDateString(data.language==="zh"?"zh-TW":"id-ID",{weekday:"long",day:"numeric",month:"long"});document.getElementById("selectedDateTx").innerHTML=rows.length?rows.map(txCard).join(""):`<div class="empty small-empty">${amount||cat?(data.language==="zh"?"沒有符合篩選條件的交易唷～ 🔍":"Tidak ada transaksi yang sesuai 🔍"):x.noDateTx}</div>`}
function renderChart(){const el=document.getElementById("expenseChart"),m={};currentMonthTx().filter(x=>x.type==="expense").forEach(x=>{const n=x.categoryName||"Lainnya";m[n]=(m[n]||0)+Number(x.amount)});const rows=Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,5);if(!rows.length){el.innerHTML=`<div class="empty">📊 ${t().noTx}</div>`;return}const max=rows[0][1];el.innerHTML=`<div class="chart-wrap">${rows.map(([n,v])=>`<div class="bar-col"><div class="bar-value">${money(v)}</div><div class="bar" style="height:${Math.max(5,v/max*78)}px"></div><div class="bar-label">${catIcon(n)} ${esc(catLabel(n))}</div></div>`).join("")}</div>`}
function txCard(x){const income=x.type==="income", transfer=x.type==="transfer";const label=transfer?"↔️ Transfer":`${catIcon(x.categoryName||"Lainnya")} ${esc(catLabel(x.categoryName||"Lainnya"))}`;const acct=transfer?`${esc(accountName(x.from))} → ${esc(accountName(x.to))}`:esc(accountName(x.accountId));return `<article class="tx"><div class="tx-icon">${transfer?"↔️":catIcon(x.categoryName||"Lainnya")}</div><div class="tx-main"><div class="tx-title">${label}</div><div class="tx-meta">${acct} · ${esc(x.date)}${x.note?` · ${esc(x.note)}`:""}</div></div><div class="tx-right"><div class="tx-amount ${income?"income":transfer?"transfer":"expense"}">${income?"+ ":transfer?"":"- "}${money(x.amount)}</div><div class="tx-actions"><button class="tx-action-icon" aria-label="${esc(t().edit)}" title="${esc(t().edit)}" onclick="editTx('${x.id}')">✏️</button><button class="tx-action-icon" aria-label="${esc(t().delete)}" title="${esc(t().delete)}" onclick="deleteTx('${x.id}')">🗑️</button></div></div></article>`}
function accountName(i){return data.accounts.find(a=>a.id===i)?.name||"—"}
function renderTransactions(){const rows=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id));if(!rows.length){document.getElementById("transactionList").innerHTML=`<div class="empty">${t().noTx}</div>`;return;}const limit=Math.min(visibleTransactionCount,rows.length);const visible=rows.slice(0,limit);const more=rows.length>limit?`<button class="show-more-tx" onclick="toggleTransactions()">${t().showMoreTransactions}</button>`:((visibleTransactionCount>5&&rows.length>5)?`<button class="show-more-tx secondary" onclick="hideOlderTransactions()">${t().showLessTransactions}</button>`:"");document.getElementById("transactionList").innerHTML=visible.map(txCard).join("")+more}
function recurringPaid(r){return r.paidPeriod===monthKey()}
function renderRecurring(){const el=document.getElementById("recurringList"),x=t();if(!data.recurring.length){el.innerHTML=`<div class="empty">${x.emptyRecurring}</div>`;return}el.innerHTML=data.recurring.map(r=>{const paid=recurringPaid(r);return `<article class="recurring-row ${paid?"paid":""}"><div class="recurring-left"><div class="recurring-icon">🧾</div><div><div class="recurring-name">${esc(r.name)}</div><div class="recurring-meta">${money(r.amount)} · ${x.date} ${r.day}</div><span class="status ${paid?"status-paid":"status-unpaid"}">${paid?x.recurringPaid:x.recurringUnpaid}</span></div></div><div class="recurring-actions">${paid?`<span class="paid-mark">✓</span>`:`<button class="mini pay-btn" onclick="markRecurringPaid('${r.id}')">${x.markPaid}</button>`}<button class="mini" onclick="editRecurring('${r.id}')">${x.edit}</button><button class="mini" onclick="deleteRecurring('${r.id}')">${x.delete}</button></div></article>`}).join("")}
function renderBudget(){const el=document.getElementById("budgetCard"),x=t(),budget=Number(data.budget||0),used=totals().ex,left=Math.max(0,budget-used);if(!budget){el.innerHTML=`<div class="planning-empty"><span>🎯</span><div><strong>${x.noBudget}</strong></div></div>`;return}const pct=Math.min(100,Math.round(used/budget*100));el.innerHTML=`<div class="planning-summary"><div><span class="small">${x.amount}</span><strong>${money(budget)}</strong></div></div><div class="planning-row"><span>${x.budgetUsed}</span><strong>${money(used)}</strong></div><div class="progress"><i style="width:${pct}%"></i></div><div class="planning-row small"><span>${x.budgetLeft}</span><strong>${money(left)}</strong></div>`}
function renderSavings(){const el=document.getElementById("savingsCard"),x=t(),target=data.target||{},goal=Number(target.amount||0),saved=Number(target.progress||0);if(!goal){el.innerHTML=`<div class="planning-empty"><span>🐷</span><div><strong>${x.savingsTitle}</strong></div></div>`;return}const pct=Math.min(100,Math.round(saved/goal*100));el.innerHTML=`<div class="planning-summary"><div><span class="small">${x.name}</span><strong>${esc(target.name||x.savingsTitle)}</strong></div></div><div class="planning-row"><span>${x.savingsTarget}</span><strong>${money(goal)}</strong></div><div class="progress"><i style="width:${pct}%"></i></div><div class="planning-row small"><span>${x.progress}</span><strong>${pct}%</strong></div>`}
function editBudget(){const x=t();openModal(x.budgetTitle,`<div class="form-grid"><div class="field"><label>${x.amount}</label>${amountInput("budgetAmount",data.budget||0)}</div><button class="primary" id="saveBudget">${x.save}</button></div>`);wireAmount("budgetAmount");document.getElementById("saveBudget").onclick=()=>{data.budget=Number(document.getElementById("budgetAmount").value)||0;saveAndClose()}}
function editSavings(){const x=t(),target=data.target||{};openModal(x.savingsTitle,`<div class="form-grid"><div class="field"><label>${x.name}</label><input id="savingsName" value="${esc(target.name||"")}" placeholder="${esc(x.savingsTitle)}"></div><div class="field"><label>${x.savingsTarget}</label>${amountInput("savingsAmount",target.amount||0)}</div><div class="field"><label>${x.savedAmount}</label>${amountInput("savingsProgress",target.progress||0)}</div><button class="primary" id="saveSavings">${x.save}</button></div>`);wireAmount("savingsAmount");wireAmount("savingsProgress");document.getElementById("saveSavings").onclick=()=>{data.target={name:document.getElementById("savingsName").value.trim(),amount:Number(document.getElementById("savingsAmount").value)||0,progress:Number(document.getElementById("savingsProgress").value)||0};saveAndClose()}}
function render(){recalc();applyLang();document.body.classList.toggle("dark",data.theme==="dark");const tt=totals(),total=data.accounts.reduce((s,a)=>s+(a.balance||0),0);document.getElementById("mainBalance").textContent=money(total);document.getElementById("income").textContent=money(tt.in);document.getElementById("expense").textContent=money(tt.ex);renderAccounts();renderCalendar();renderChart();renderRecurring();renderTransactions();renderBudget();renderSavings()}
function accountForm(a={}){const x=t();return `<div class="compact-form"><div class="field"><label>${x.name}</label><input id="fName" value="${esc(a.name||"")}" autocomplete="off"></div><div class="field"><label>${x.type}</label><select id="fType"><option value="cash">${x.cash}</option><option value="bank">${x.bank}</option><option value="ewallet">${x.ewallet}</option></select></div><div class="field"><label>${x.opening}</label>${amountInput("fOpening",a.openingBalance||0)}</div><button class="primary" id="saveA">${x.save}</button></div>`}
function addAccount(existing){const x=t();openModal(existing?.id?x.edit:x.accountAdd,accountForm(existing||{}));if(existing?.type)document.getElementById("fType").value=existing.type;wireAmount("fOpening");document.getElementById("saveA").onclick=()=>{const name=document.getElementById("fName").value.trim()||x.accounts;const openingBalance=Number(document.getElementById("fOpening").value)||0;if(existing?.id){existing.name=name;existing.type=document.getElementById("fType").value;existing.openingBalance=openingBalance}else data.accounts.push({id:id(),name,type:document.getElementById("fType").value,openingBalance});saveAndClose()}}
function editAccount(i){addAccount(data.accounts.find(a=>a.id===i))}
function deleteAccount(i){if(data.accounts.length<=1)return;const account=data.accounts.find(a=>a.id===i);if(!account)return;if(confirm(t().deleteConfirm)){data.accounts=data.accounts.filter(a=>a.id!==i);data.transactions=data.transactions.filter(z=>z.accountId!==i&&z.from!==i&&z.to!==i);persist();openWallet(account.type);toast(t().deleted);}}
function txForm(x={}){return `<div class="compact-form"><div class="tx-type-switch"><button type="button" class="tx-type-btn" data-type="expense" aria-label="${t().expenseType}" title="${t().expenseType}">💸</button><button type="button" class="tx-type-btn" data-type="income" aria-label="${t().incomeType}" title="${t().incomeType}">💰</button><button type="button" class="tx-type-btn transfer-btn" data-type="transfer" aria-label="${t().transactions}" title="${t().transactions}">🔄</button></div><input type="hidden" id="fTxType" value="expense"><div id="txFields"></div><button class="primary" id="saveTx">${t().save}</button></div>`}
function fillTxFields(x={}){const type=document.getElementById("fTxType").value,cats=data.categories.filter(c=>c.kind===type),a=[...data.accounts].sort((u,v)=>{const order={cash:0,bank:1,ewallet:2};return (order[u.type]??9)-(order[v.type]??9)||u.name.localeCompare(v.name)}),icons={cash:"💵",bank:"🏦",ewallet:"💳"};let html=`<div class="field"><label>${t().amount}</label>${amountInput("fAmount",x.amount||0)}</div>`;if(type==="transfer")html+=`<div class="row"><div class="field"><label>From</label><select id="fFrom">${a.map(z=>`<option value="${z.id}">${icons[z.type]||"👛"} ${esc(z.name)}</option>`).join("")}</select></div><div class="field"><label>To</label><select id="fTo">${a.map(z=>`<option value="${z.id}">${icons[z.type]||"👛"} ${esc(z.name)}</option>`).join("")}</select></div></div>`;else html+=`<div class="row"><div class="field"><label>${t().account}</label><select id="fAccount">${a.map(z=>`<option value="${z.id}">${icons[z.type]||"👛"} ${esc(z.name)}</option>`).join("")}</select></div><div class="field"><label>${t().category}</label><select id="fCat">${cats.map(c=>`<option value="${c.id}">${catIcon(c.name)} ${esc(catLabel(c.name))}</option>`).join("")}</select></div></div>`;html+=`<div class="tx-date-note"><div class="field date-field"><label>${t().date}</label><input id="fDate" type="date" value="${x.date||data.selectedDate||today()}"></div><div class="field note-field"><label>${t().note}</label><input id="fNote" value="${esc(x.note||"")}" placeholder="${data.language==="zh"?"選填":"Opsional"}"></div></div>`;document.getElementById("txFields").innerHTML=html;wireAmount("fAmount")}
function addTx(existing){openModal(existing?t().edit:t().transactionAdd,txForm(existing||{}));const startType=existing?.type||"expense";document.getElementById("fTxType").value=startType;const buttons=[...document.querySelectorAll(".tx-type-btn")];const setType=type=>{document.getElementById("fTxType").value=type;buttons.forEach(b=>b.classList.toggle("active",b.dataset.type===type));fillTxFields(existing||{})};buttons.forEach(b=>b.onclick=()=>setType(b.dataset.type));setType(startType);if(existing)setTimeout(()=>{if(existing.type==="transfer"){document.getElementById("fFrom").value=existing.from;document.getElementById("fTo").value=existing.to}else{document.getElementById("fAccount").value=existing.accountId;document.getElementById("fCat").value=existing.categoryId}},0);document.getElementById("saveTx").onclick=()=>{const type=document.getElementById("fTxType").value,amount=Number(document.getElementById("fAmount").value)||0;if(amount<=0)return;const z={id:existing?.id||id(),type,amount,date:document.getElementById("fDate").value,note:document.getElementById("fNote").value.trim()};if(type==="transfer"){z.from=document.getElementById("fFrom").value;z.to=document.getElementById("fTo").value}else{z.accountId=document.getElementById("fAccount").value;z.categoryId=document.getElementById("fCat").value;z.categoryName=data.categories.find(c=>c.id===z.categoryId)?.name||"Lainnya"}if(existing)data.transactions=data.transactions.filter(a=>a.id!==existing.id);data.transactions.push(z);saveAndClose()}}
function toggleTransactions(){visibleTransactionCount+=10;renderTransactions()}
function hideOlderTransactions(){visibleTransactionCount=5;renderTransactions()}
function editTx(i){addTx(data.transactions.find(x=>x.id===i))}
function deleteTx(i){if(confirm(t().deleteConfirm)){data.transactions=data.transactions.filter(x=>x.id!==i);persist();toast(t().deleted)}}
function recurringForm(r={}){const x=t();return `<div class="form-grid"><div class="field"><label>${x.name}</label><input id="rName" value="${esc(r.name||"")}"></div><div class="field"><label>${x.amount}</label>${amountInput("rAmount",r.amount||0)}</div><div class="field"><label>${x.account}</label><select id="rAccount">${data.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join("")}</select></div><div class="field"><label>${x.category}</label><select id="rCat">${data.categories.filter(c=>c.kind==="expense").map(c=>`<option value="${c.id}">${catIcon(c.name)} ${esc(catLabel(c.name))}</option>`).join("")}</select></div><div class="field"><label>${x.date}</label><select id="rDay">${Array.from({length:31},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join("")}</select></div><button class="primary" id="saveR">${x.save}</button></div>`}
function addRecurring(r){const x=t();openModal(r?x.edit:x.recurringAdd,recurringForm(r||{}));if(r){document.getElementById("rAccount").value=r.accountId;document.getElementById("rCat").value=r.categoryId;document.getElementById("rDay").value=r.day}wireAmount("rAmount");document.getElementById("saveR").onclick=()=>{const obj=r||{id:id(),paidPeriod:null};obj.name=document.getElementById("rName").value.trim()||x.recurringAdd;obj.amount=Number(document.getElementById("rAmount").value)||0;obj.accountId=document.getElementById("rAccount").value;obj.categoryId=document.getElementById("rCat").value;obj.day=Number(document.getElementById("rDay").value);if(!r)data.recurring.push(obj);saveAndClose()}}
function editRecurring(i){addRecurring(data.recurring.find(r=>r.id===i))}
function deleteRecurring(i){if(confirm(t().deleteConfirm)){data.recurring=data.recurring.filter(r=>r.id!==i);persist();toast(t().deleted)}}
function markRecurringPaid(i){const r=data.recurring.find(r=>r.id===i);if(!r||recurringPaid(r))return;const cat=data.categories.find(c=>c.id===r.categoryId);data.transactions.push({id:id(),type:"expense",amount:+r.amount,date:today(),note:data.language==="zh"?`固定支出：${r.name}`:`Tagihan tetap: ${r.name}`,accountId:r.accountId,categoryId:r.categoryId,categoryName:cat?.name||"Lainnya",recurringId:r.id,recurringPeriod:monthKey()});r.paidPeriod=monthKey();persist();toast(t().saved)}
function settings(){const x=t();openModal(x.settings,`<div class="settings-item"><strong>${x.language}</strong><select id="setLang"><option value="id">Bahasa Indonesia</option><option value="zh">繁體中文</option></select></div><div class="settings-item"><strong>${x.currency}</strong><select id="setCur"><option>IDR</option><option>MYR</option><option>NTD</option></select></div><div class="settings-item"><strong>${x.theme}</strong><select id="setTheme"><option value="light">${x.light}</option><option value="dark">${x.dark}</option></select></div><div class="settings-item"><strong>${x.data}</strong><div class="row"><button class="primary secondary" id="backupBtn">${x.backup}</button><button class="primary secondary" id="restoreBtn">${x.restore}</button><input id="restoreFile" type="file" accept="application/json" hidden></div></div><div class="settings-item"><strong>${x.danger}</strong><button class="primary danger" id="reset">${x.reset}</button></div>`);document.getElementById("setLang").value=data.language;document.getElementById("setCur").value=data.currency;document.getElementById("setTheme").value=data.theme;document.getElementById("setLang").onchange=e=>{data.language=e.target.value;persist();settings()};document.getElementById("setCur").onchange=e=>{data.currency=e.target.value;persist();settings()};document.getElementById("setTheme").onchange=e=>{data.theme=e.target.value;persist();settings()};document.getElementById("backupBtn").onclick=backupData;document.getElementById("restoreBtn").onclick=()=>document.getElementById("restoreFile").click();document.getElementById("restoreFile").onchange=restoreData;document.getElementById("reset").onclick=()=>{if(confirm(x.resetConfirm)){localStorage.removeItem(KEY);data=load();render();closeModal();toast(x.deleted)}}}
function manageCategories(){
  const x=t();
  const render=()=>{
    const expense=data.categories.filter(c=>c.kind==="expense"),income=data.categories.filter(c=>c.kind==="income");
    const group=(title,list)=>`<div class="cat-group"><div class="cat-group-title">${title}</div>${list.map(c=>`<div class="category-row"><div class="category-info"><span class="category-icon">${esc(c.emoji||"📝")}</span><div><strong>${esc(c.name)}</strong><div class="cat-sub">${esc(c.nameZh||c.name)}</div></div></div><button class="mini" onclick="editCategory('${c.id}')">${x.edit}</button></div>`).join("")}</div>`;
    document.getElementById("modalBody").innerHTML=`<div class="category-manager"><button class="primary" id="addCategoryBtn">＋ ${x.add} ${x.category}</button>${group(x.expenseType,expense)}${group(x.incomeType,income)}</div>`;
    document.getElementById("addCategoryBtn").onclick=()=>categoryForm();
  };
  openModal(x.manageCategories,"");
  render();
}
function categoryForm(existing){
  const x=t(), c=existing||{kind:"expense",name:"",nameZh:"",emoji:"📝"};
  openModal(existing?x.edit:x.add+" "+x.category,`<div class="form-grid"><div class="field"><label>${x.name} (Indonesia)</label><input id="catName" maxlength="30" value="${esc(c.name)}" placeholder="Contoh: Kopi"></div><div class="field"><label>繁體中文</label><input id="catNameZh" maxlength="30" value="${esc(c.nameZh||"")}" placeholder="例如：咖啡"></div><div class="field"><label>Emoji</label><input id="catEmoji" maxlength="4" value="${esc(c.emoji||"📝")}" placeholder="🍜" inputmode="text"></div><div class="field"><label>${x.type}</label><select id="catKind"><option value="expense">${x.expenseType}</option><option value="income">${x.incomeType}</option></select></div><button class="primary" id="saveCategory">${x.save}</button><button class="primary secondary" id="cancelCategory">${x.cancel}</button></div>`);
  document.getElementById("catKind").value=c.kind;
  document.getElementById("saveCategory").onclick=()=>{
    const name=document.getElementById("catName").value.trim(), nameZh=document.getElementById("catNameZh").value.trim()||name, emoji=document.getElementById("catEmoji").value.trim()||"📝", kind=document.getElementById("catKind").value;
    if(!name)return;
    if(existing){
      existing.name=name; existing.nameZh=nameZh; existing.emoji=emoji; existing.kind=kind;
      data.transactions.forEach(tx=>{if(tx.categoryId===existing.id)tx.categoryName=name});
    }else data.categories.push({id:id(),name,nameZh,emoji,kind});
    persist(); closeModal(); toast(x.saved); setTimeout(manageCategories,0);
  };
  document.getElementById("cancelCategory").onclick=manageCategories;
}
function editCategory(i){const c=data.categories.find(c=>c.id===i);if(c)categoryForm(c)}
function backupData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`catatan-keuangan-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(t().exported)}
function restoreData(e){const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);data={...data,...x};persist();closeModal();toast(t().imported)}catch{alert("File tidak valid")}};reader.readAsText(f)}
function selectDate(ds){data.selectedDate=ds;persist()}
function shiftCalendar(step){const [y,m]=data.calendarMonth.split("-").map(Number);const d=new Date(y,m-1+step,1);data.calendarMonth=monthKey(d);data.selectedDate=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`;persist()}
document.getElementById("addAccountBtn").onclick=()=>addAccount();document.getElementById("editBudgetBtn").onclick=editBudget;document.getElementById("editSavingsBtn").onclick=editSavings;document.getElementById("addTransactionBtn").onclick=()=>addTx();document.getElementById("fab").onclick=()=>addTx();document.getElementById("addRecurringBtn").onclick=()=>addRecurring();document.getElementById("prevMonth").onclick=()=>shiftCalendar(-1);document.getElementById("nextMonth").onclick=()=>shiftCalendar(1);document.getElementById("hideBalanceBtn").onclick=()=>{data.hidden=!data.hidden;persist()};document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{if(n.dataset.tab==="settings")settings();else if(n.dataset.tab==="categories")manageCategories();else if(n.dataset.tab==="transactions")document.getElementById("calendarTitle").scrollIntoView({behavior:"smooth"});else scrollTo({top:0,behavior:"smooth"})});
render();
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
